package com.boredream.AlgBase;


import java.util.Arrays;

public class Sort {

    public static void main(String[] args) {

//        char[] charArray = "afldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsacuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunlfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunouncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsacluncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpununcqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpuninupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpungcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuripionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuriafldkslkjafdsiojonuncqweiornucgdskfjgcpunoinupionuasfdlcjknsaclfjkascfusfdnyocuynoiuysndioufynpqwiuri".toCharArray();
//        char[] charArray = "uynoiuysndioufynpqwiuri".toCharArray();
        char[] charArray = "837491526".toCharArray();
        quickSort2(charArray);
        System.out.println(charArray);
    }

    private static char kthHigh(char[] charArray, int k) {
        return kthHigh(charArray, k, 0, charArray.length - 1);
    }

    private static char kthHigh(char[] charArray, int k, int start, int end) {
        // 首位作为比较
        char comppare = charArray[start];
        // 从次卫到末尾，左右分割，小的左，大的右
        int lo = start;
        int high = end;
        while (true) {
            while (charArray[lo] <= comppare && lo < end) lo++;
            while (charArray[high] > comppare && high > start) high--;
            if (lo >= high) break;
            exchange(charArray, lo, high);
        }
        exchange(charArray, start, high);
        // 已经分左右了，kth大的看当前分割的位置，如果正好是 length - k 个数，就返回，否则继续找左或右半边即可
        if (high > charArray.length - k) {
            // 继续从左边找
            return kthHigh(charArray, k, start, high - 1);
        } else if (high < charArray.length - k) {
            // 从右边找
            return kthHigh(charArray, k, high + 1, end);
        } else {
            return charArray[high];
        }
    }

    private static void sortWithTime(char[] charArray) {
        long start = System.currentTimeMillis();
        System.out.println(charArray);
        shellSort(charArray);
        System.out.println(System.currentTimeMillis() - start);
        System.out.println(charArray);
    }

    // 选择排序
    public static void chooseSort(char[] charArray) {
        // 每次循环获取最小数，然后和第一个数交换
        // 每轮结束后指针下移 O(n^2)
        for (int i = 0; i < charArray.length - 1; i++) {
            int minIndex = i;
            for (int j = i + 1; j < charArray.length; j++) {
                if (charArray[j] < charArray[minIndex]) {
                    minIndex = j;
                }
            }
            exchange(charArray, minIndex, i);
        }
    }

    // 冒泡排序
    public static void bubbleSort(char[] charArray) {
        // 每次循环两两比较交换，让最大数在最后一位
        for (int i = 0; i < charArray.length - 1; i++) {
            for (int j = 0; j < charArray.length - i - 1; j++) {
                if (charArray[j] > charArray[j + 1]) exchange(charArray, j, j + 1);
            }
        }
    }

    // 插入排序
    public static void insertSort(char[] charArray) {
        // 每轮循环让当前数字回头找到刚好比自己大的数插在它左侧，保证当前数字起始位置左侧是有序的
        for (int i = 1; i < charArray.length; i++) {
            for (int j = i; j > 0; j--) {
                // 只要左侧数字>=自己，就交换。插入+右移
                if (charArray[j - 1] < charArray[j]) break;
                exchange(charArray, j, j - 1);
            }
        }
    }

    // 希尔排序 （插入排序的进化版）
    public static void shellSort(char[] charArray) {
        int h = 1;
        while (h < charArray.length / 3) h = h * 3 + 1;
        // 用 h * 3 + 1 是保证间隔数字是质数，防止公约数重复
        // 如果是简单 * 2，那么第一轮比如是间隔8，第二轮间隔4，每两个间隔还是会重复第一轮已经重排的数字，浪费，所以~
        while (h >= 1) {
            for (int i = h; i < charArray.length; i++) {
                for (int j = i; j >= h && charArray[j] < charArray[j - h]; j -= h) {
                    exchange(charArray, j, j - h);
                }
            }
            h = h / 3;
        }
    }

    // 归并排序-自顶向下
    public static void mergeSort(char[] charArray) {
        // 利用分治法的思想，最基本的step是merge，即可以把两个「有序」的小数组，合并成一个「有序」的大数组
        // 迭代重复这个步骤，就可以搞定了
        mergeSort(charArray, 0, charArray.length - 1);
    }

    public static void mergeSort(char[] charArray, int left, int right) {
        // length <= 2时，直接排序子数组
        // 可省略，直接用merge步骤替代
        if (right - left <= 1) {
            if (charArray[left] > charArray[right]) {
                exchange(charArray, left, right);
            }
            return;
        }

        // 递归二分，各自排序
        int mid = left + (right - left) / 2;
        mergeSort(charArray, left, mid);
        mergeSort(charArray, mid + 1, right);
        // 二分排序后合并结果，递归回头
        merge(charArray, left, mid, mid + 1, right);
    }

    // 归并排序-自底向上
    public static void mergeSortB2T(char[] charArray) {
        // 同理，分别1、2、4分组两两有序合并
        for (int size = 1; size < charArray.length; size *= 2) {
            // 每次迭代子数组长度翻倍
            for (int i = 0; i < charArray.length - size; i += size * 2) {
                // 按子数组长度两两有序合并
                merge(charArray, i, i + size - 1,
                        Math.min(charArray.length - 1, i + size), // 注意边界
                        Math.min(charArray.length - 1, i + 2 * size - 1));
            }
        }
    }

    private static void merge(char[] charArray, int left1, int right1, int left2, int right2) {
        // 每组left~right都是有序的，且两组挨着
        // 双指针排序，merge需要借助额外数组
        char[] copyArray = Arrays.copyOf(charArray, charArray.length);
        int index1 = left1;
        int index2 = left2;
        for (int i = left1; i <= right2; i++) {
            // 双指针，谁小用谁。一个用完用另一个
            if (index1 > right1) {
                charArray[i] = copyArray[index2++];
            } else if (index2 > right2) {
                charArray[i] = copyArray[index1++];
            } else if (copyArray[index1] < copyArray[index2]) {
                charArray[i] = copyArray[index1++];
            } else {
                charArray[i] = copyArray[index2++];
            }
        }
    }

    // 快速排序
    public static void quickSort(char[] charArray) {
        // 跟归并法一样，利用分治的概念，但是是先保证两个大集合，左半边都小于右半边，依次二分下去
        quickSort(charArray, 0, charArray.length - 1);
    }

    public static void quickSort(char[] charArray, int lo, int hi) {
        if (lo >= hi) return; // 递归一定要有结束条件
        int j = partition(charArray, lo, hi);
        // 以参照数位置为准，再次二分，j的位置一定正确，不用再加入排序
        quickSort(charArray, lo, j - 1);
        quickSort(charArray, j + 1, hi);
    }

    private static int partition(char[] charArray, int lo, int hi) {
        int i = lo + 1;
        int j = hi;
        char v = charArray[lo]; // 取第一个位置内容作为参照
        while (true) {
            while (charArray[i] <= v && i < hi) i++;
            while (charArray[j] >= v && lo < j) j--;
            if(i >= j) break;
            exchange(charArray, i, j);
        }
        exchange(charArray, lo, j);
        return j;
    }

    private static int partition4(char[] charArray, int lo, int hi) {
        int i = lo + 1;
        int j = hi;
        char v = charArray[lo]; // 取第一个位置内容作为参照
        while (i <= j) {
            // FIXME 如果i=j，且[j]<v，则俩内循环都不进i，j不变，死循环
            // TODO 外循环true，在内循环完成后再判断条件break
            while (charArray[i] <= v && i < hi) i++;
            while (charArray[j] >= v && lo < j) j--;
            if (i < j) exchange(charArray, i, j);
        }
        exchange(charArray, lo, j);
        return j;
    }

    private static int partition3(char[] charArray, int lo, int hi) {
        int i = lo + 1;
        int j = hi;
        char v = charArray[lo]; // 取第一个位置内容作为参照
        while (i < j) {
            // FIXME 当lo+1=hi时，因为i=lo+1，所以不会进入i<j循环，则最终lo和j(hi)直接无比较交换，可能出错
            // TODO 外循环 i<= j
            while (charArray[i] <= v && i < hi) i++;
            while (charArray[j] >= v && lo < j) j--;
            if (i < j) exchange(charArray, i, j);
        }
        exchange(charArray, lo, j);
        return j;
    }

    private static int partition2(char[] charArray, int lo, int hi) {
        int i = lo + 1;
        int j = hi;
        char v = charArray[lo]; // 取第一个位置内容作为参照
        while (i < j) {
            // FIXME i<j => i一直左移到j，j不变，最后lo,j交换出错
            // FIXME i<=j => 可能数组越界
            // TODO 判断 i < hi and j > lo
            while (charArray[i] <= v && i < j) i++;
            while (charArray[j] >= v && i < j) j--;
            if (i < j) exchange(charArray, i, j);
        }
        exchange(charArray, lo, j);
        return j;
    }

    private static int partition1(char[] charArray, int lo, int hi) {
        int i = lo + 1;
        int j = hi;
        char v = charArray[lo]; // 取第一个位置内容作为参照
        while (i <= j) {
            // FIXME 可能出现 charArray[i] = charArray[j] = v的情况，则死循环
            // TODO 判断[j] >= v
            while (charArray[j] > v && i <= hi) j--;
            while (charArray[i] < v && lo <= j) i++;
            if (i < j) exchange(charArray, i, j);
        }
        exchange(charArray, lo, i - 1);
        return j;
    }

    // 快速排序，第二种方法
    private static void quickSort2(char[] charArray) {
        quickSort2(charArray, 0, charArray.length - 1);
    }

    private static void quickSort2(char[] charArray, int start, int end) {
        if (start >= end - 1) return; // start超过end，或者start只是在end前一位，没必要再排序
        char compare = charArray[start]; // step1.取第一个值作为比较目标
        int swapIndex = start + 1;
        for (int i = start + 1; i <= end; i++) {
            // step2.挨个比较后面所有的值，比他小的放左边，比他大的放右边
            // 左右分大小算法，使用一个swapIndex记录位置，每次发现小的了交换该位置并+1
            char target = charArray[i];
            if (target < compare) {
                exchange(charArray, swapIndex++, i);
            }
        }
        // step3.遍历完以后，交换对比位置数据和swapIndex-1。即对比数据左右分为两组，分别小于以及大于等于自己
        exchange(charArray, start, swapIndex - 1);

        // step4.之后对拆成两半的两组集合再次进行如上的操作，swapIndex-1是比较值，固定不动
        quickSort2(charArray, start, swapIndex - 2);
        quickSort2(charArray, swapIndex, end);
    }

    private static void exchange(char[] charArray, int i, int j) {
        char temp = charArray[i];
        charArray[i] = charArray[j];
        charArray[j] = temp;
    }
}
